//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessDetail
    {
        public BusinessDetail()
        {
            this.Reservations = new HashSet<Reservation>();
            this.ReservationGuests = new HashSet<ReservationGuest>();
            this.ReservationMessageRules = new HashSet<ReservationMessageRule>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ReservationBusinessId { get; set; }
        public Nullable<short> BusinessTypeId { get; set; }
        public string BusinessName { get; set; }
        public string LogoPath { get; set; }
        public string OpenDayFrom { get; set; }
        public string OpenDayTo { get; set; }
        public Nullable<System.TimeSpan> OpenHourFrom { get; set; }
        public Nullable<System.TimeSpan> OpenHourTo { get; set; }
        public Nullable<bool> IsLimitSizePerHour { get; set; }
        public Nullable<short> LimitSizePerHour { get; set; }
        public Nullable<bool> IsLimitTimePerReservation { get; set; }
        public Nullable<short> MinLimitTimePerReservation { get; set; }
        public Nullable<short> MaxLimitTimePerReservation { get; set; }
        public Nullable<bool> IsLimitSizePerGroup { get; set; }
        public Nullable<short> LimitSizePerGroup { get; set; }
        public string ShortUrl { get; set; }
        public Nullable<bool> IsDLScanEnabled { get; set; }
        public Nullable<bool> IsChargeEnabled { get; set; }
        public Nullable<bool> IsSeatmapEnabled { get; set; }
        public Nullable<short> NoOfSeatRows { get; set; }
        public Nullable<short> NoOfSeatColumns { get; set; }
        public Nullable<int> PassTemplateId { get; set; }
        public string VirtualNo { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
    
        public virtual BusinessType BusinessType { get; set; }
        public virtual ReservationBusiness ReservationBusiness { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<ReservationGuest> ReservationGuests { get; set; }
        public virtual ICollection<ReservationMessageRule> ReservationMessageRules { get; set; }
    }
}
