//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessType
    {
        public BusinessType()
        {
            this.BusinessDetails = new HashSet<BusinessDetail>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BusinessDetail> BusinessDetails { get; set; }
    }
}
