//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcertReservation
    {
        public ConcertReservation()
        {
            this.ConcertGuests = new HashSet<ConcertGuest>();
            this.ConcertReservationMessages = new HashSet<ConcertReservationMessage>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> ConcertId { get; set; }
        public Nullable<short> Size { get; set; }
        public string Seatings { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public string ConfirmationNo { get; set; }
        public Nullable<int> GuestTypeId { get; set; }
    
        public virtual ICollection<ConcertGuest> ConcertGuests { get; set; }
        public virtual GuestType GuestType { get; set; }
        public virtual ICollection<ConcertReservationMessage> ConcertReservationMessages { get; set; }
        public virtual Concert Concert { get; set; }
    }
}
