//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryStatu
    {
        public int DeliveryStatusId { get; set; }
        public string msisdn { get; set; }
        public string to { get; set; }
        public string network_code { get; set; }
        public string messageId { get; set; }
        public string price { get; set; }
        public string status { get; set; }
        public string scts { get; set; }
        public string err_code { get; set; }
        public Nullable<System.DateTime> message_timestamp { get; set; }
        public string Project { get; set; }
    }
}
