//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyMessage
    {
        public int LoyaltyMessageId { get; set; }
        public Nullable<long> GuestId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MessageDateTime { get; set; }
        public string MessageFrom { get; set; }
        public string MessageTo { get; set; }
        public Nullable<bool> IsMessageRead { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string StatusMessage { get; set; }
        public string MessageId { get; set; }
        public string ErrorText { get; set; }
        public string ClientRef { get; set; }
    
        public virtual GuestInfo GuestInfo { get; set; }
    }
}
