//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageReply
    {
        public long MessageReply1 { get; set; }
        public Nullable<long> WaitListId { get; set; }
        public string type { get; set; }
        public string text { get; set; }
        public string MessageTo { get; set; }
        public string msisdn { get; set; }
        public string networkcode { get; set; }
        public string messageid { get; set; }
        public Nullable<System.DateTime> messagetimestamp { get; set; }
    }
}
