//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationMessage
    {
        public int Id { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public string MessageSent { get; set; }
        public Nullable<System.DateTime> MessageSentDateTime { get; set; }
        public Nullable<System.Guid> MessageSentBy { get; set; }
        public string MessageReplied { get; set; }
        public Nullable<System.DateTime> MessageRepliedDateTime { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
