//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationGuest
    {
        public ReservationGuest()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> BusinessDetailId { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual BusinessDetail BusinessDetail { get; set; }
    }
}
