//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.ReservationMessages = new HashSet<ReservationMessage>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> BusinessDetailId { get; set; }
        public Nullable<System.Guid> ReservationGuestId { get; set; }
        public Nullable<int> GuestTypeId { get; set; }
        public Nullable<short> Size { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeTo { get; set; }
        public Nullable<System.DateTime> UtcDateTimeFrom { get; set; }
        public Nullable<System.DateTime> UtcDateTimeTo { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    
        public virtual GuestType GuestType { get; set; }
        public virtual ICollection<ReservationMessage> ReservationMessages { get; set; }
        public virtual ReservationGuest ReservationGuest { get; set; }
        public virtual BusinessDetail BusinessDetail { get; set; }
    }
}
