//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantTable
    {
        public RestaurantTable()
        {
            this.WaitLists = new HashSet<WaitList>();
        }
    
        public int TableId { get; set; }
        public Nullable<int> RestaurantChainId { get; set; }
        public Nullable<int> TableTypeId { get; set; }
        public string TableNumber { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<System.Guid> AssignedTo { get; set; }
    
        public virtual RestaurantChain RestaurantChain { get; set; }
        public virtual TableType TableType { get; set; }
        public virtual ICollection<WaitList> WaitLists { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
