//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.RestaurantChains = new HashSet<RestaurantChain>();
        }
    
        public int RestaurantId { get; set; }
        public string BusinessName { get; set; }
        public string LogoPath { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<System.DateTime> SignUpDate { get; set; }
        public Nullable<System.Guid> ConfirmationToken { get; set; }
        public Nullable<bool> isConfirmed { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
    
        public virtual PlanType PlanType { get; set; }
        public virtual ICollection<RestaurantChain> RestaurantChains { get; set; }
    }
}
