//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantChain
    {
        public RestaurantChain()
        {
            this.ReadyMessages = new HashSet<ReadyMessage>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.UsersInRestaurants = new HashSet<UsersInRestaurant>();
            this.VisitMessages = new HashSet<VisitMessage>();
            this.VisitMessageSents = new HashSet<VisitMessageSent>();
            this.RestaurantClosedDays = new HashSet<RestaurantClosedDay>();
            this.RestaurantTables = new HashSet<RestaurantTable>();
            this.WaitLists = new HashSet<WaitList>();
            this.GuestInfoes = new HashSet<GuestInfo>();
        }
    
        public int RestaurantChainId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public Nullable<short> AverageWaitTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RestaurantNumber { get; set; }
        public string TableLayoutPath { get; set; }
        public Nullable<System.TimeSpan> OpeningHour { get; set; }
        public Nullable<System.TimeSpan> ClosingHour { get; set; }
        public Nullable<int> WaittimeInterval { get; set; }
    
        public virtual ICollection<ReadyMessage> ReadyMessages { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<UsersInRestaurant> UsersInRestaurants { get; set; }
        public virtual ICollection<VisitMessage> VisitMessages { get; set; }
        public virtual ICollection<VisitMessageSent> VisitMessageSents { get; set; }
        public virtual ICollection<RestaurantClosedDay> RestaurantClosedDays { get; set; }
        public virtual ICollection<RestaurantTable> RestaurantTables { get; set; }
        public virtual ICollection<WaitList> WaitLists { get; set; }
        public virtual ICollection<GuestInfo> GuestInfoes { get; set; }
    }
}
