//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffType
    {
        public StaffType()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public short StaffTypeId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
