//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableType
    {
        public TableType()
        {
            this.RestaurantTables = new HashSet<RestaurantTable>();
        }
    
        public int TableTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> MaxSeating { get; set; }
    
        public virtual ICollection<RestaurantTable> RestaurantTables { get; set; }
    }
}
