//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.UsersInRestaurants = new HashSet<UsersInRestaurant>();
            this.WaitLists = new HashSet<WaitList>();
            this.RestaurantTables = new HashSet<RestaurantTable>();
        }
    
        public System.Guid UserId { get; set; }
        public Nullable<int> RestaurantChainId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> LastAccessDateTime { get; set; }
        public Nullable<bool> IsPasswordChanged { get; set; }
        public Nullable<short> StaffTypeId { get; set; }
        public Nullable<System.Guid> ReservationBusinessId { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<System.Guid> ConfirmationToken { get; set; }
    
        public virtual ICollection<UsersInRestaurant> UsersInRestaurants { get; set; }
        public virtual RestaurantChain RestaurantChain { get; set; }
        public virtual ICollection<WaitList> WaitLists { get; set; }
        public virtual StaffType StaffType { get; set; }
        public virtual ICollection<RestaurantTable> RestaurantTables { get; set; }
        public virtual ReservationBusiness ReservationBusiness { get; set; }
    }
}
