//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatQ.core.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> isUserActive { get; set; }
        public Nullable<bool> isUserDeleted { get; set; }
        public Nullable<System.DateTime> LastAccessDateTime { get; set; }
        public Nullable<bool> IsPasswordChanged { get; set; }
        public Nullable<int> RestaurantChainId { get; set; }
        public Nullable<bool> isRestautantChainActive { get; set; }
        public string RestaurantNumber { get; set; }
        public string FullName { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<bool> isAccountConfirmed { get; set; }
        public string BusinessName { get; set; }
        public Nullable<System.Guid> ConfirmationToken { get; set; }
        public string LogoPath { get; set; }
        public Nullable<short> StaffTypeId { get; set; }
        public string Title { get; set; }
    }
}
