//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userinfo.dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public string Email { get; set; }
        public System.Guid UserId { get; set; }
        public int RegistrationSourceId { get; set; }
        public string StripeId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Avatar { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        public virtual User User { get; set; }
    }
}
